# Generated by Django 4.2.7 on 2023-11-22 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catelog', '0001_initial'),
        ('units', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_date', models.DateTimeField()),
                ('qty', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catelog.variation')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='units.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.status')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.order')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catelog.variation')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='production_item', to='units.unit')),
            ],
        ),
    ]
