# Generated by Django 4.2.7 on 2023-11-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_unit_data'),
        ('catelog', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produce',
            new_name='Output',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='produce_date',
            new_name='output_date',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
