# Generated by Django 4.2.7 on 2023-12-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_modify_formula_placeholder'),
        ('recipes', '0012_alter_ingredient_options_and_more'),
        ('production', '0004_outputaddon'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.output')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='units.unit')),
            ],
        ),
    ]
