# Generated by Django 4.2.7 on 2023-12-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_remove_outputpackaging_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='outputaddon',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='outputpackaging',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
