# Generated by Django 4.2.7 on 2023-12-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_output_unit_cost_alter_outputaddon_unit_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='qty',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='outputpackaging',
            name='qty',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
