# Generated by Django 4.2.7 on 2023-11-22 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '__first__'),
        ('units', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Status categories',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='purchasing.statuscategory')),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='purchasing.status')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_unit_qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchase_qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recipes.ingredient')),
                ('package_unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='po_item', to='units.unit')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseorder')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='purchasing.status')),
            ],
        ),
    ]
