# Generated by Django 4.2.7 on 2023-11-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_vendor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='sequence',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
