# Generated by Django 4.2.7 on 2023-11-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_status_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
