# Generated by Django 4.2.7 on 2023-12-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_alter_item_package_unit_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
