# Generated by Django 4.2.7 on 2023-12-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_rename_status_id_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='package_unit_qty',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='package_unit',
            new_name='unit',
        ),
    ]
