# Generated by Django 4.2.7 on 2023-12-26 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_modify_formula_placeholder'),
        ('recipes', '0012_alter_ingredient_options_and_more'),
        ('purchasing', '0007_rename_package_unit_qty_item_qty_and_more'),
    ]

    operations = [
        migrations.RenameModel('Item', 'POItem')
    ]
