# Generated by Django 4.2.7 on 2023-12-26 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_modify_formula_placeholder'),
        ('purchasing', '0008_poitem_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='units.unit'),
        ),
    ]
