# Generated by Django 4.2.7 on 2023-11-24 01:46

from django.db import migrations
from ..models import Recipe, ProductRecipe

def migrate_data(apps, schema_editor):
    recipeList = Recipe.objects.all()
    for recipe in recipeList:
        ProductRecipe(recipe=recipe, product_variation=recipe.product_variation, recipe_number=recipe.recipe_number, make_qty=recipe.make_qty, make_unit=recipe.make_unit, notes=recipe.notes).save()

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_name_alter_recipe_product_variation_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
