# Generated by Django 4.2.7 on 2023-11-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_migrate_data_to_product_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='make_qty',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='make_unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='product_variation',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_number',
        ),
    ]
