# Generated by Django 4.2.7 on 2023-12-02 00:24

from django.db import migrations, models
from ..models import RecipeIngredient

def migrate_data(apps, schema_editor):
    ingList = RecipeIngredient.objects.all()
    for ing in ingList:
        ing.qty = ing.qty_numerator / ing.qty_denominator
        ing.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_make_qty_remove_recipe_make_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(migrate_data)
    ]
