# Generated by Django 4.2.7 on 2023-12-02 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipeingredient_qty_alter_ingredient_price_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='qty_denominator',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='qty_numerator',
        ),
    ]
