# Generated by Django 4.2.7 on 2023-12-02 07:53

from django.db import migrations, models
import django.db.models.deletion
from ..models import UnitCategoryConversion

def migrate_data(apps, schema_editor):
    cat_conversions = UnitCategoryConversion.objects.all()
    for cc in cat_conversions:
        cc.category_from = cc.unit_from.category
        cc.category_to = cc.unit_to.category
        cc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_alter_config_item'),
        ('recipes', '0007_remove_recipeingredient_qty_denominator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='baking_temp',
            new_name='baking_temp_degrees',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='temp_unit',
            new_name='baking_temp_unit',
        ),
        migrations.AddField(
            model_name='unitcategoryconversion',
            name='category_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='category_from', to='units.unitcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitcategoryconversion',
            name='category_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='category_to', to='units.unitcategory'),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_data)
    ]
