# Generated by Django 4.2.7 on 2023-12-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_baking_temp_recipe_baking_temp_degrees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitcategoryconversion',
            name='unit_from',
        ),
        migrations.RemoveField(
            model_name='unitcategoryconversion',
            name='unit_to',
        ),
    ]
