# Generated by Django 4.2.7 on 2023-12-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_unitcategoryconversion_unit_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='price_per_unit',
            new_name='cost_per_unit',
        ),
    ]
