# Generated by Django 4.2.7 on 2023-12-02 00:10

from django.db import migrations, models
from config.models import Config

def create_data(apps, schema_editor):
    Config(item="company_name", value="The Bake Shop").save()
    Config(item="company_tag_line", value="Tasty Treats").save()

class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_config_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='id',
        ),
        migrations.AlterField(
            model_name='config',
            name='item',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.RunPython(create_data)
    ]
