# Generated by Django 4.2.7 on 2023-11-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='recipe_batch_size',
        ),
    ]
