# Generated by Django 4.2.7 on 2023-12-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0002_remove_variation_recipe_batch_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
