# Generated by Django 4.2.7 on 2023-12-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0003_alter_variation_cost_alter_variation_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='cost',
        ),
    ]
