# Generated by Django 4.2.7 on 2023-12-17 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_productrecipe_active'),
        ('units', '0006_modify_formula_placeholder'),
        ('catelog', '0004_remove_variation_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='units.unit')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catelog.variation')),
            ],
        ),
        migrations.CreateModel(
            name='VariationAddOns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='units.unit')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catelog.variation')),
            ],
        ),
    ]
