# Generated by Django 4.2.7 on 2023-12-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_modify_formula_placeholder'),
        ('recipes', '0011_productrecipe_active'),
        ('catelog', '0005_variationpackaging_variationaddons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariationAddOns',
            new_name='VariationAddOn',
        ),
    ]
