# Generated by Django 4.2.7 on 2023-12-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0006_rename_variationaddons_variationaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationaddon',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variationpackaging',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
