# Generated by Django 4.2.7 on 2023-12-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0007_variationaddon_qty_variationpackaging_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationaddon',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variationpackaging',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
