# Generated by Django 4.2.7 on 2023-12-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0008_variationaddon_active_variationpackaging_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ('product', 'name')},
        ),
    ]
