# Generated by Django 4.2.7 on 2023-12-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0009_alter_variation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationaddon',
            name='qty',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variationpackaging',
            name='qty',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
