# Generated by Django 4.2.7 on 2023-11-24 03:05

from django.db import migrations, models
import django.db.models.deletion

from ..models import Customer

def create_data(apps, schemas):
    Customer(name="Walk In").save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0003_unit_data'),
        ('catelog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.status')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catelog.variation')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_item', to='units.unit')),
            ],
        ),
        migrations.RunPython(create_data)
    ]
