# Generated by Django 4.2.7 on 2023-12-26 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_modify_formula_placeholder'),
        ('sales', '0003_itemaddon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='units.unit'),
        ),
    ]
