# Generated by Django 4.2.7 on 2023-11-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseunit',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='baseunit',
            old_name='unit_id',
            new_name='unit',
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_system',
            field=models.CharField(choices=[('Imperial', 'Imperial'), ('Metric', 'Metric'), ('Universal', 'Universal')], default='Metric', max_length=9),
        ),
    ]
