# Generated by Django 4.2.7 on 2023-12-01 22:36

from django.db import migrations, models
from ..models import Config

def create_data(apps, schema_editor):
    cfg1 = Config(item="max_fraction_denominator", value="16")
    cfg1.save()

class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_unit_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('item', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='unit',
            name='abbr',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.RunPython(create_data)
    ]
