# Generated by Django 4.2.7 on 2023-12-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_config_alter_unit_abbr_alter_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='item',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
